startData = [
  {
    imgOnScreen: 'img/start.gif',
    quizCardTitle: 'Hello there!',
    quizCardTxt: 'Press >>NEXT<< to start quizzing. Good luck, pal!',
    answer_1:
      'Submit your answer by choosing it with the corresponding button and hit >>CONFIRM<< !',
    answer_2: '',
    answer_3: '',
    answer_4: '',
  },
];

quizData = [
  {
    imgOnScreen: 'img/q01.gif',
    questionLED: 'q1LED',
    question: 'The Beatles on a usual tuesday. Which song do we "see" here?',
    answer_1: 'Now and Then',
    answer_2: 'Norwegian Wood',
    answer_3: 'Strawberry Fields',
    answer_4: 'Lovely Rita',
    right_anwer: 2,
  },
  {
    imgOnScreen: 'img/q02.gif',
    questionLED: 'q2LED',
    question: 'The Dude is a big fan of which of the following Bands?',
    answer_1: 'Creedence Clearwater Revival',
    answer_2: 'Eagles',
    answer_3: 'Everly Brothers',
    answer_4: 'Neil Young',
    right_anwer: 0,
  },
  {
    imgOnScreen: 'img/q03.xxx',
    questionLED: 'q3LED',
    question: 'What is the self-made guitar of QUEEN-Member Brian May called?',
    answer_1: 'Silver Bullet',
    answer_2: 'Black Thunder',
    answer_3: 'Golden Axe',
    answer_4: 'Red Special',
    right_anwer: 3,
  },
  {
    imgOnScreen: 'img/q04.xxx',
    questionLED: 'q4LED',
    question: 'Which famous guitarist was a member of the band Cream?',
    answer_1: 'Eric Clapton',
    answer_2: 'Jimmy Page',
    answer_3: 'Jeff Beck',
    answer_4: 'Jimi Hendrix',
    right_answer: 0,
  },
  {
    imgOnScreen: 'img/q05.xxx',
    questionLED: 'q5LED',
    question: 'Where was Exile on Main Street recorded?',
    answer_1: 'a ranchs stable',
    answer_2: 'a Villas basement',
    answer_3: 'a submarine studio',
    answer_4: 'a rooftop bar',
    right_answer: 1,
  },
  // 2 more!

  {
    imgOnScreen: 'img/q06.xxx',
    questionLED: 'q06LED',
    question: 'What is the name of this well suited problem-solver?',
    answer_1: 'Mr. Brown',
    answer_2: 'Mr. Black',
    answer_3: 'Mr. Wolf',
    answer_4: 'Mr. Fox',
    right_answer: 3,
  },
  {
    imgOnScreen: 'img/q07.xxx',
    questionLED: 'q07LED',
    question: 'John Wick is known by a sinister nickname. Whatn is it?',
    answer_1: 'Baba Yaga',
    answer_2: 'Ghost',
    answer_3: 'Grim Reaper',
    answer_4: 'Dark Shadow',
    right_answer: 3,
  },

  {
    imgOnScreen: 'img/q08.xxx',
    questionLED: 'q8LED',
    question: 'What is the hex code for his last name (Walter White)?',
    answer_1: '#OOOOOO',
    answer_2: '#IIIIII',
    answer_3: '#111111',
    answer_4: '#000000',
    right_answer: 3,
  },
  {
    imgOnScreen: 'img/q09.xxx',
    questionLED: 'q9LED',
    question: 'HAL 9000 is the antagonist of which movie?',
    answer_1: 'Blade Runner',
    answer_2: 'The Matrix',
    answer_3: '2001: A Space Odyssey',
    answer_4: 'Interstellar',
    right_answer: 2,
  },
  {
    imgOnScreen: 'img/q10.xxx',
    questionLED: 'q10LED',
    question: 'Where did Luke survive an Icestorm in the snow-desert on Hoth?',
    answer_1: 'In a cave',
    answer_2: 'In a Tauntauns body',
    answer_3: 'In an igloo',
    answer_4: 'Whithin a Force barrier',
    right_answer: 1,
  },
  {
    imgOnScreen: 'img/q11.xxx',
    questionLED: 'q11LED',
    question: 'Which of the following adventures was not made by LucasArts?',
    answer_1: 'The Secret of Monkey Island',
    answer_2: 'Grim Fandango',
    answer_3: 'Indiana Jones & the Fate of Atlantis',
    answer_4: 'Beneath a Steel Sky',
    right_answer: 3,
  },
  {
    imgOnScreen: 'img/q12.xxx',
    questionLED: 'q12LED',
    question: 'When was the Nintendo Entertainment System (NES) released?',
    answer_1: '1985',
    answer_2: '1986',
    answer_3: '1987',
    answer_4: '1988',
    right_answer: 0,
  },
  {
    imgOnScreen: 'img/q13.xxx',
    questionLED: 'q13LED',
    question:
      'Which Streetfighter characters have almost the same fighting-style?',
    answer_1: 'Honda & Chun-Li',
    answer_2: 'Zangief & Guile',
    answer_3: 'Dhalsim & Blanka',
    answer_4: 'Ryu & Ken',
    right_answer: 3,
  },
  {
    imgOnScreen: 'img/q14.xxx',
    questionLED: 'q14LED',
    question: 'Who is not a GTA-Titles main character?',
    answer_1: 'Tommy Vercetti',
    answer_2: 'Niko Bellic',
    answer_3: 'Trevor Phillips',
    answer_4: 'John MacTavish',
    right_answer: 3,
  },
  {
    imgOnScreen: 'img/q15.xxx',
    questionLED: 'q15LED',
    question: 'Wat ist the final spoken word in &apos;The Last Of Us&apos;?',
    answer_1: 'okay',
    answer_2: 'promise',
    answer_3: 'truth',
    answer_4: 'swear',
    right_answer: 3,
  },
  {
    imgOnScreen: 'img/q16.xxx',
    questionLED: 'q16LED',
    question: 'What is the actual first name of the Cookie Monster?',
    answer_1: 'Roy',
    answer_2: 'Max',
    answer_3: 'Sid',
    answer_4: 'Hugo',
    right_answer: 2,
  },
  {
    imgOnScreen: 'img/q17.xxx',
    questionLED: 'q17LED',
    question:
      'What is the answer to the meaning of life, the universe, and everything?',
    answer_1: '24',
    answer_2: '42',
    answer_3: '0',
    answer_4: '1',
    right_answer: 1,
  },
  {
    imgOnScreen: 'img/q18.xxx',
    questionLED: 'q18LED',
    question: 'How many Fabergé Eggs do exist?',
    answer_1: '48',
    answer_2: '53',
    answer_3: '69',
    answer_4: '50',
    right_answer: 1,
  },
  {
    imgOnScreen: 'img/q19.xxx',
    questionLED: 'q19LED',
    question: 'Which language does R2-D2 speak?',
    answer_1: 'Astromech Binary',
    answer_2: 'Droid-101',
    answer_3: 'Andr0-ID',
    answer_4: 'Rebublic-Mech-Tongue',
    right_answer: 0,
  },
  {
    imgOnScreen: 'img/q20.xxx',
    questionLED: 'q20LED',
    question: 'Which wave-form is commonly used to get a fat bass sound?',
    answer_1: 'sawtooth-wave',
    answer_2: 'sine-wave',
    answer_3: 'square-wave',
    answer_4: 'pulse-wave',
    right_answer: 1,
  },
];
